### ISSUE TITLE
如何进行指定单个成员删除

### ISSUE THREAD

**Issue by wannaliang** [ArcsoftEscErd/ArcfaceDemo_Android_V3_0#1]
如何进行指定单个成员删除，比如根据成员姓名

**Comment by ArcsoftEscErd** [comment]
demo中存放人脸数据的方式是：

**Comment by SkyStonePan** [comment]
Demo中注册的人脸存放的位置是context.getFilesDir()目录，
其中特征数据存放在该目录下的："register" + File.separator + "features"目录，
注册照存放在该目录下的： "register" + File.separator + "imgs"目录。
也就是说，对于姓名为name的人脸，其特征数据的文件路径为：
context.getFilesDir() + File.separator + "register" + File.separator + "features" + File.separator + name
其注册照的文件路径为：
context.getFilesDir() + File.separator + "register" + File.separator + "imgs" + File.separator + name.jpg；
若需要删除，手动删除这两个文件，并同时删除内存中的数据

**Comment by wannaliang** [comment]
好的，我试试，感谢

**Comment by wannaliang** [comment]
这两个文件只能手动删除吗？

**Comment by wannaliang** [comment]
可以了，谢谢
